sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
env:
  global:
  - APP_USER=abhiesa
  - APP_NAME=ng5-sb-crud
  - IMAGE_NAME=abhiesa/ng5-sb-crud
  - DOCKER_REGISTRY_USER=abhiesa
  - secure: kvhLJ3RAMTbbZcHoXoi8Ony7GhlZgF35Bj/ItdKhzBtRmm+CeXaVeI/9KR9qKjkLjie+Oji+99L/6UgyucPfqkalwFH5tnKQMm2gsWqOs3oY73UYM5W8pApJLUd87P+zDToo6zq+ECbPxbWglaIrEjNpfA6Gent/qdRKGXt3BWO5rjILO+vcG1YwgEpZWdLk8PchjnDeellAVLeU5Vt6TspLNxCGo/cDAUCVrBkqoVijUeTySFSe4LHSKdkQt8RDc1DjQW75ijBPpKfqihhLblY4Qo2hi0acPISslRM5b74kRbAYO+G/JDC5YtUHPj5dHR46W3szK56HAfkoBcgxhFjhbmtQsX8/KNw96r/RMmBFesaf7MZwo5kLG9RcSN3PThePp7Lpf5n6lmIW/NIiKqNemEyMm+Zv8G4FTR41/FR9hRNGQZmgNVAHmve7rMxkDI692IFUc25dv2giv+PvRsu5ZSbCf2QDE1qjcsQJGI/hZiOY6x2xpsnnAi/D2LtcUzE5FAkAvuMkKJA87A+hpg95q7+IdyaHJVUMs1jnbKZW0FZ+QmKT1RxKOoY4hYFQXHPoSupnfOrqBmNBkejzStVq/v6Sg2CaLvCu/Tfp0qdQ88V18XRAz1ighvbyRXPjl4KmU/QCkA57sXYdhGgRAG8G9fR0Xnh9HIODbr7J3UE=
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
before_script:
- git config user.name "$COMMIT_AUTHOR_NAME"
- git config user.email "$COMMIT_AUTHOR_EMAIL"
- export COMMIT_MESSAGE=`git log -1 --oneline`
script:
- mvn clean compile test package verify
after_success:
- mvn clean test jacoco:report coveralls:report
notifications:
  email: false
deploy:
  provider: bintray
    file: "descriptor.json"
    user: "abhiesa"
    dry-run: false
    skip_cleanup: true
    on:
      tags: true
    key:
      secure: n230dH2F1iEJWOQqSDiGYK4O52KVZY3JfoPbAWDVooqKSu8z8R6MnZi9D/HPQ6ITfdSVGD9wvPcTuCFbIg+zJ6nlG4TYAWWyvs6Iif0eagqS1O9IfwYm9Gz9JNa5EYIKeUsiieA/q0+0Gn592tVIgDDg9w5PEq1VmOKwXUG+lrKA2m3bj5g/j5PQJVN6oyVD5zG4gCP0upFfDyu9shUdeJsW5FwVPQqbbL++pNkC48xRoheo0fzzKxeapbfL6apqkPZTCeAsmUNJW0YElQB/OE+OLioHmayhW9kQk5vtZNy3r5jrZ9rcZ8NSOrNU9SpdzNLFFRrzrVq/4uwSVWL8xTSA0J2kd7kaXpMnKtSz/Ipcdm+Xgl1v5dBvfgTA7BXwhvQ8Jef1SxM/JQ0lyVS/8YybQEyNL7CPqi5Y/UVxV3+Jpu1heaU+TAAZlECwwmqvpI+gMN1D22IVoBe6YvjG8fto7KHiJUG0FggA2jYFG2Mv7S2B3HfAwGzYc8hz3GBJgK8Qw6pxDrgPek+4wd97S8sTmqoY/9JqYQ0wAeYEFjhqafF2ImAfbNVxQUvQmjIVjrRu6e5lTbPvGPoSCXFE76a0oAfgcKRqIaFRjBxY/CNnyX9IxD6eKiJ3g4PuMwG93d0gM0ppNs9hQPVfz+n3WZ1tt5yOLQnUSS7Ogo9jYeo=
