sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
env:
  global:
  - APP_USER=abhiesa
  - APP_NAME=ng5-sb-crud
  - IMAGE_NAME=abhiesa/ng5-sb-crud
  - DOCKER_REGISTRY_USER=abhiesa
  - secure: kvhLJ3RAMTbbZcHoXoi8Ony7GhlZgF35Bj/ItdKhzBtRmm+CeXaVeI/9KR9qKjkLjie+Oji+99L/6UgyucPfqkalwFH5tnKQMm2gsWqOs3oY73UYM5W8pApJLUd87P+zDToo6zq+ECbPxbWglaIrEjNpfA6Gent/qdRKGXt3BWO5rjILO+vcG1YwgEpZWdLk8PchjnDeellAVLeU5Vt6TspLNxCGo/cDAUCVrBkqoVijUeTySFSe4LHSKdkQt8RDc1DjQW75ijBPpKfqihhLblY4Qo2hi0acPISslRM5b74kRbAYO+G/JDC5YtUHPj5dHR46W3szK56HAfkoBcgxhFjhbmtQsX8/KNw96r/RMmBFesaf7MZwo5kLG9RcSN3PThePp7Lpf5n6lmIW/NIiKqNemEyMm+Zv8G4FTR41/FR9hRNGQZmgNVAHmve7rMxkDI692IFUc25dv2giv+PvRsu5ZSbCf2QDE1qjcsQJGI/hZiOY6x2xpsnnAi/D2LtcUzE5FAkAvuMkKJA87A+hpg95q7+IdyaHJVUMs1jnbKZW0FZ+QmKT1RxKOoY4hYFQXHPoSupnfOrqBmNBkejzStVq/v6Sg2CaLvCu/Tfp0qdQ88V18XRAz1ighvbyRXPjl4KmU/QCkA57sXYdhGgRAG8G9fR0Xnh9HIODbr7J3UE=
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
before_script:
 - git config user.name "$COMMIT_AUTHOR_NAME"
 - git config user.email "$COMMIT_AUTHOR_EMAIL"
 - export COMMIT_MESSAGE=`git log -1 --oneline`
script:
- mvn clean compile test package verify
after_success:
- mvn clean test jacoco:report coveralls:report
notifications:
  email: false

